
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (1,null,0,'RES_DYNA_MENU','Talks','{1}',1,'Talks','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (2,'TALKS',1,'RES_MENU','Talks','/communication/talks/home',1,'Talks','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (3,'TALKS_PROFILE',1,'RES_MENU','프로필','/communication/talks/profile',2,'사용자의 프로필 및 톡을 조회합니다.','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (4,'USER_CAPA',3,'RES_SCREEN','개인정량분석','-',1,null,'NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (5,'TALKS_FOLLOWER',1,'RES_MENU','동료찾기','/communication/talks/user',3,'동료찾기','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (6,'TALKS_GROUP',1,'RES_DYNA_MENU','그룹','{1}',4,'톡스그룹메뉴','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (7,'TALKS_GROUP_SEARCH',6,'RES_MENU','그룹찾기','/communication/talks/group/search',1,'그룹찾기','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (8,'TALKS_GROUP_MGR',6,'RES_MENU','그룹관리','/communication/talks/group',2,'그룹관리','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (9,null,0,'RES_DYNA_MENU','마이페이지','{1}',2,'MyPage','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (10,'MY_PAGE',9,'RES_MENU','마이페이지','/user/mypage',1,'나의 페이지','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (11,'MY_CALENDAR',9,'RES_MENU','내 달력','/calendar',2,'내 달력','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (12,'USER_TASK',9,'RES_MENU','내 할일','/user/task',3,'TODO','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (13,null,0,'RES_DYNA_MENU','게시판','{1}',3,'게시판','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (14,'ALL_NOTICE',13,'RES_DYNA_MENU','전체공지사항','{1}',1,'전체 공지사항','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (16,'ALL_BOARD',13,'RES_DYNA_MENU','공유게시판','{1}',2,'전체 게시판 메뉴','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (18,'BOARD_MGR',13,'RES_MENU','공유게시판관리','/communication/board',4,'공유게시판 관리','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (19,null,0,'RES_DYNA_MENU','회의실','{1}',4,'회의실','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (20,'MEETING_ROOM_RESERVATION',19,'RES_MENU','회의실 예약','/meetingroom/reservation',1,'회의실 예약','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (21,null,0,'RES_DYNA_MENU','시스템관리','{1}',5,'시스템관리','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (22,null,21,'RES_DYNA_MENU','조직','{1}',1,'조직','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (23,'SYS_COMPANY',22,'RES_MENU','업체등록','/company',1,'업체를 관리합니다.','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (24,'SYS_DEPARTMENT',22,'RES_MENU','부서등록','/department',2,'부서관리','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (25,'SYS_ORG_USER',21,'RES_DYNA_MENU','사용자','{1}',2,'사용자관리','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (26,'SYS_USER',25,'RES_MENU','사용자등록','/user',1,'사용자 등록','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (27,'SYS_APPLICANT',25,'RES_MENU','사용자승인','/applicant',2,'시스템의 사용자 등록요청을 관리합니다.','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (28,'SYS_ATTENDANCE',25,'RES_MENU','사용자근태조회','/user/attendance',3,'근태조회','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (29,'MGR_JOB',21,'RES_DYNA_MENU','업무','{1}',3,'업무','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (30,'MGR_PROJECT',29,'RES_MENU','프로젝트등록','/mgr/project',1,'프로젝트의 기본정보를 관리합니다.','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (31,'MGR_PROGRAM',29,'RES_MENU','프로그램등록','/mgr/program',2,'프로그램 기본정보를 관리합니다.','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (32,'MGR_PRODUCT',29,'RES_MENU','제품등록','/mgr/product',3,'제품정보를 관리합니다.','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (33,'INFOSYS_ARTIFACT',29,'RES_MENU','산출물 검색','/infosystem/artifact',4,'산출물 검색','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (34,'MEETING_ROOM',29,'RES_MENU','회의실 관리','/meetingroom/management',5,'회의실 관리','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (35,'SYS_BUDGET_ACCOUNT_TITLE',29,'RES_MENU','계정과목 관리','/system/accountTitle',6,'계정과목 관리','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (36,null,21,'RES_DYNA_MENU','템플릿관리','{1}',3,'템플릿관리','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (37,'SYS_REPORT',36,'RES_MENU','보고서관리','/system/report',1,'리포트 출력물을 관리한다.','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (38,'SYS_FONT',36,'RES_MENU','보고서폰트관리','/system/font',2,'출력물폰트관리','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (39,'DASHBOARD_TEMPLATE',36,'RES_MENU','현황판템플릿관리','/system/dashboardtemplate',3,'현황판템플릿관리','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (40,'SYS_WORKPATH_TEMPLATE',36,'RES_MENU','공정템플릿관리','/system/workpathtemplate',4,'공정템플릿관리','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (41,'SYS_ARTIFACT',36,'RES_MENU','산출물양식등록','/system/artifact',5,'산출물 양식 등록','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (42,'SYS_WORKFLOW',21,'RES_MENU','워크플로우관리','/system/workflow',4,'워크플로우 관리','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (43,null,21,'RES_DYNA_MENU','배치','{1}',5,'배치','NO'
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (44,'SYS_BATCH',43,'RES_MENU','코드생산성 배치','/system/batch/scm',1,'배치관리','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (45,'SYS_COMMON_BATCH',43,'RES_MENU','공통배치','/system/batch/common',2,'시스템 공통 배치 서비스','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (46,'SYS_USER_ROLE',21,'RES_DYNA_MENU','메뉴/권한','{1}',6,'메뉴/권한 관리','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (47,'SYS_MENU',46,'RES_MENU','메뉴관리','/system/menu',1,'메뉴 및 화면정보를 관리합니다.','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (48,'SYS_ROLE',46,'RES_MENU','역할관리','/system/role',2,'사용자의 역할을 관리합니다.','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (49,'SYS_AUTHORITY',46,'RES_MENU','권한관리','/system/authority',3,'역할별 메뉴 접근 권한을 관리합니다.','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (50,null,21,'RES_DYNA_MENU','설정','{1}',7,'설정','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (51,'SYS_CODESET',50,'RES_MENU','코드관리','/system/codeset',1,'시스템코드를 관리합니다.','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (52,'NOTIFICATION_CONFIGURATION',50,'RES_MENU','통지관리','/notification/configuration',2,null,'NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (53,'PRODUCT_MYREQUEST',0,'RES_MENU','내요청','/product/{pdid}/myrequest',1,'내 요청 관리','PD');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (54,'PRODUCT_NEWREQUEST',0,'RES_MENU','새요청','/product/{pdid}/newrequest',2,'새 요청 관리','PD');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (55,'PRODUCT_REQUIREMENT',0,'RES_MENU','요구사항','/product/{pdid}/requirement',3,'요구사항 백로그 관리','PD');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (56,'PRODUCT_DEFECT',0,'RES_MENU','결함','/product/{pdid}/defect',4,'결함 백로그 관리','PD');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (57,'PRODUCT_ASSIGN',0,'RES_MENU','작업할당','/product/{pdid}/assign',5,'백로그의 작업할당','PD');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (58,'PRODUCT_CATEGORY',0,'RES_MENU','카테고리','/product/{pdid}/category',6,'카테고리','PD');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (59,'PRODUCT_ACCESSOR',0,'RES_MENU','접근관리','/product/{pdid}/accessor',7,'제품 접근관리','PD');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (60,null,0,'RES_DYNA_MENU','프로그램 정보','{1}',1,'프로그램 정보','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (61,'PG_INFO',60,'RES_MENU','기본정보','/program/{pgid}/info',1,'프로그램 일반정보와 구성정보를 보여주고 편집한다.','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (62,'PG_ACCESSOR',60,'RES_MENU','접근관리','/program/{pgid}/accessor',2,'프로그램 접근관리','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (63,'PG_CONCLUSION',60,'RES_MENU','종결처리','/program/{pgid}/conclusion',3,'프로그램을 종료처리한다.','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (64,null,0,'RES_DYNA_MENU','인력구성','{1}',2,'인력구성','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (65,'PG_COMPANY',64,'RES_MENU','수행업체현황','/program/{pgid}/company',1,'각 프로젝트에 참여하는 수행업체 현황을 조회한다.','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (66,'PG_PARTICIPANT',64,'RES_MENU','참여인력현황','/program/{pgid}/participant',2,'각 프로젝트에 참여하는 팀원들을 보여준다.','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (67,'PG_MEMBER',64,'RES_MENU','구성원','/program/{pgid}/member',3,'프로젝트별 팀 구성원을 조회한다.','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (68,null,0,'RES_DYNA_MENU','진척현황','{1}',3,'진척현황','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (69,'PG_PROGRESS',68,'RES_MENU','진척현황','/program/{pgid}/statistics/wbs',1,'프로그램 현황판을 조회한다.','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (70,'PG_GRAPH',68,'RES_MENU','프로젝트 상태','/program/{pgid}/statistics/graph',2,'프로젝트별 상태를 그래프로 조회한다.','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (71,null,0,'RES_DYNA_MENU','작업추세','{1}',4,'작업추세','PG'
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (72,'PG_ESTIMATION',71,'RES_MENU','작업현황','/program/{pgid}/estimation',1,'프로그램 작업 현황판을 조회한다.','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (73,'PG_BURNDOWN',71,'RES_MENU','소멸차트','/program/{pgid}/burndown',2,'프로젝트별 반복 소멸차트를 조회한다.','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (74,null,0,'RES_DYNA_MENU','원가총괄','{1}',5,'원가총괄','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (75,'PG_BUDGET_ACCOUNT',74,'RES_MENU','원가관리현황','/program/{pgid}/statistics/budgetAccount',2,'원가관리현황','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (76,null,0,'RES_DYNA_MENU','주요이슈','{1}',6,'주요이슈','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (77,'PG_ISSUE',76,'RES_MENU','이슈현황','/program/{pgid}/statistics/issue',1,'각 프로젝트의 이슈목록을 보여준다.','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (78,'PG_RISK',76,'RES_MENU','위험현황','/program/{pgid}/statistics/risk',2,'각 프로젝트의 위험목록을 보여준다.','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (79,null,0,'RES_DYNA_MENU','주요결함','{1}',7,'주요결함','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (80,'PG_DEFECT',79,'RES_MENU','결함현황','/program/{pgid}/statistics/defect',1,'각 프로젝트의 결함목록을 보여준다.','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (81,null,0,'RES_DYNA_MENU','의사소통성향','{1}',8,'의사소통성향','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (82,'PG_TALKSTENDENCY',81,'RES_MENU','의사소통','/program/{pgid}/talkstendency',6,'프로젝트별 구성원들의 의사소통을 조회한다.','PG');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (83,'PJT',0,'RES_DYNA_MENU','프로젝트 정보','{1}',1,'프로젝트 정보','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (84,'PJT_INFO',83,'RES_MENU','기본정보','/project/{pjid}',1,'프로젝트 정보를 관리합니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (85,'PJT_CONTRACT',83,'RES_MENU','계약정보','/project/{pjid}/contract',2,'프로젝트 계약정보를 관리합니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (86,'PJT_COMPANY',83,'RES_MENU','수행업체','/project/{pjid}/company',3,'프로젝트 수행업체정보를 관리합니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (87,'PJT_TEAM_MGR',83,'RES_MENU','팀구성','/project/{pjid}/team',4,'프로젝트 팀을 관리합니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (88,'PJT_PARTICIPANT',83,'RES_MENU','참여인력','/project/{pjid}/participant',5,null,'PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (89,null,83,'RES_DYNA_MENU','참여인력변경','{1}',7,'','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (90,'PJT_PARTICIPANT_CHANGE',89,'RES_MENU','변경내역','/project/{pjid}/participant/change',3,'프로젝트 참여인력의 변경을 관리합니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (91,'PJT_PARTICIPANT_REQUEST',89,'RES_MENU','변경요청','/project/{pjid}/participant/request',1,'참여인력 변경요청을 관리합니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (92,'PJT_PARTICIPANT_APPROVE',89,'RES_MENU','변경승인','/project/{pjid}/participant/approve',2,'참여인력 변경요청에 대한 승인및 거절을 관리합니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (93,'PJT_BUDGET_ACCOUNT',83,'RES_DYNA_MENU','원가관리','{1}',8,'','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (94,'PJT_BUDGET_ACCOUNT_STATS',93,'RES_MENU','원가총괄','/project/{pjid}/budgetAccount/stats/all',1,'','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (95,'PJT_BUDGET_ACCOUNT_DETAIL_STATS',93,'RES_MENU','계정과목상세','/project/{pjid}/budgetAccount/detailstat',2,null,'PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (96,'PJT_BUDGET_ACCOUNT_BOOK_INPUT',93,'RES_SCREEN','출납형태 입력','/project/{pjid}/budgetAccount/excution',3,null,'PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (97,'PJT_BUDGET_ACCOUNT_MONTH_INPUT',93,'RES_SCREEN','윌별비용 입력','/project/{pjid}/budgetAccount/payroll',4,null,'PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (98,'PJT_ACCESSOR',459,'RES_MENU','접근관리','/project/{pjid}/accessor',2,'프로젝트 접근관리','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (99,'PJT_CONCLUSION',83,'RES_MENU','종결처리','/project/{pjid}/conclusion',10,'프로젝트 종료를 관리하는 메뉴입니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (100,null,0,'RES_DYNA_MENU','현황','{1}',2,'현황판템플릿관리','PJ'
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (101,'PJT_STATS',100,'RES_MENU','프로젝트통계','/project/{pjid}/statistics',1,'프로젝트의 현황을 조회합니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (102,'PJT_DASHBOARD',100,'RES_DYNA_MENU','프로젝트현황판','{1}',2,'프로젝트현황판','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (104,'WORK_RELEASE',100,'RES_MENU','작업현황판','/project/{pjid}/release',3,'메소다 프로젝트 반복현황','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (105,'WORK_ESTIMATION',100,'RES_DYNA_MENU','예측그래프','{1}',4,'작업 예측그래프','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (106,'WORK_ESTIMATION_HISTORY',105,'RES_MENU','진척률이력','/project/{pjid}/estimation/history',1,'진척률 이력','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (107,'WORK_ESTIMATION_TREND',105,'RES_MENU','진척률추세','/project/{pjid}/estimation/trend',2,'진척률 추세','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (108,'WORK_ESTIMATION_PATTERN',105,'RES_MENU','진척률패턴','/project/{pjid}/estimation/pattern',3,'진척률 패턴','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (109,'PJT_ATTENDANCE',100,'RES_MENU','근태현황','/project/{pjid}/attendance',5,'','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (110,'PJT_REPORT_PRINT',100,'RES_MENU','보고서 출력','/project/{pjid}/report',7,'보고서 출력','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (111,'PJT_DASHBOARD_MGR',100,'RES_MENU','현황판관리','/project/{pjid}/dashboard',6,'현황판관리','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (112,null,0,'RES_DYNA_MENU','의사소통','{1}',3,'이해관계자들간의 의사소통 공간입니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (113,'PJT_TALKS',112,'RES_MENU','Talks','/project/{pjid}/talks',1,'프로젝트 참여자들의 업무 의사소통 도구입니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (114,'PJT_NOTICE',112,'RES_DYNA_MENU','공지사항','{1}',2,null,'PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (116,'PJT_BOARD',112,'RES_DYNA_MENU','게시판','{1}',3,'게시판','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (118,'PJT_REPORT',112,'RES_DYNA_MENU','보고서','{1}',4,null,'PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (120,'PJT_BOARD_MANAGER',112,'RES_DYNA_MENU','관리자게시판','{1}',5,'관리자게시판','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (122,'BOARD_MGR',112,'RES_MENU','게시판관리','/project/{pjid}/board',6,'프로젝트 게시판을 관리합니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (123,null,0,'RES_DYNA_MENU','요구사항','{1}',4,'요구사항 ','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (124,'PJT_REQUIREMENT',123,'RES_MENU','요구사항관리','/project/{pjid}/requirement',1,'요구사항관리','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (125,'PJT_REQUIREMENT_CR',123,'RES_MENU','요구사항변경관리','/project/{pjid}/requirement/changerequest',2,'요구사항변경관리','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (126,'PJT_REQUIREMENT_SHEET',123,'RES_MENU','요구사항평가서작성','/project/{pjid}/requirement/sheet',3,'요구사항평가서','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (127,'PJT_REQUIREMENT_EVAL',123,'RES_MENU','요구사항평가','/project/{pjid}/requirement/evaluation',4,'요구사항평가','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (128,null,0,'RES_DYNA_MENU','WBS','{1}',5,'WBS','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (129,'PJT_WBS_MGR',128,'RES_MENU','WBS 관리','/project/{pjid}/wbs/management',1,'WBS등록','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (130,'PJT_WBS_PROGRESS',128,'RES_MENU','WBS 진척현황','/project/{pjid}/wbs/progress',2,'WBS진척관리','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (131,'PJT_WBS_ASSIGN',128,'RES_MENU','WBS 작업할당','/project/{pjid}/wbs/assign/select',3,'WBS를 작업으로 할당한다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (132,'PJT_MILESTONE',128,'RES_MENU','마일스톤','/project/{pjid}/milestone',4,'프로젝트의 마일스톤 정보를 관리 할 수 있습니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (133,'WORK',0,'RES_DYNA_MENU','작업','{1}',6,'작업정보를 관리합니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (134,'WORK_ITERATION',133,'RES_MENU','반복','/project/{pjid}/iteration',1,'작업 반복','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (135,'WORK_LIST',133,'RES_MENU','작업목록','/project/{pjid}/workitem',2,'작업목록을 관리합니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (136,'WORK_BURNDOWN',133,'RES_MENU','소멸차트','/project/{pjid}/burndown',3,'작업 소멸차트','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (137,'WORK_SETTINGS',133,'RES_DYNA_MENU','작업환경설정','{1}',4,'작업 환경을 관리하는 메뉴입니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (138,'WORK_SETTINGS_CATEGORY',137,'RES_MENU','카테고리','/project/{pjid}/environment/category',5,'카테고리를 관리하는 메뉴입니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (139,'WORK_SETTINGS_ITERATION',137,'RES_MENU','반복기간','/project/{pjid}/environment/iterationperiod',6,'반복기간을 관리하는 메뉴입니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (140,'WORK_SETTINGS_BASIS',137,'RES_MENU','기초생산성','/project/{pjid}/environment/basisPerformance',7,'기초생산성을 관리하는 메뉴입니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (141,'WORK_SETTINGS_EXTENSIONS',137,'RES_MENU','작업 연계설정','/project/{pjid}/environment/extensions',8,'원격 Vizend 정보를 관리한다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (142,null,0,'RES_DYNA_MENU','산출물','{1}',7,'산출물','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (143,'PJT_WORKPATH',142,'RES_MENU','공정관리','/project/{pjid}/workpath',1,'공정을 관리하는 메뉴입니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (144,'PJT_ARTIFACT',142,'RES_MENU','산출물관리','/project/{pjid}/artifact',2,'프로젝트 산출물을 등록/조회 합니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (145,null,0,'RES_DYNA_MENU','위험현황','{1}',8,'위험현황','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (146,'PJT_RISK',145,'RES_MENU','위험','/project/{pjid}/risk',1,'위험','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (147,'PJT_ISSUE',145,'RES_MENU','이슈','/project/{pjid}/issue',2,'이슈','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (148,null,0,'RES_DYNA_MENU','품질','{1}',9,'결함','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (150,'STATS',0,'RES_MENU','정량분석','{1}',11,'업무 정보현황을 제공합니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (151,'PJT_CAPA_CODE',150,'RES_MENU','코드생산성','{1}',1,'프로젝트 코드생산성','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (152,'PJT_CAPA_CODE_SUM',151,'RES_MENU','생산성요약','/project/{pjid}/capa/code/summary',1,null,'PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (153,'PJT_CAPA_CODE_LOC',151,'RES_MENU','LoC','/project/{pjid}/capa/code/loc',2,null,'PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (154,'PJT_CAPA_CODE_LOC_ANAL',151,'RES_MENU','개발자LoC분석','/project/{pjid}/capa/code/locAnalysis',3,null,'PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (155,'PJT_CAPA_CODE_FILECOUNT',151,'RES_MENU','파일개수','/project/{pjid}/capa/code/filecount',4,null,'PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (156,'PJT_CAPA_CODE_COMMIT',151,'RES_MENU','활동량','/project/{pjid}/capa/code/commit',5,null,'PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (157,'PJT_CAPA_CODE_TIME',151,'RES_MENU','활동시간','/project/{pjid}/capa/code/commitTime',6,null,'PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (158,'PJT_CAPA_CODE_FILESTAT',151,'RES_MENU','파일통계','/project/{pjid}/capa/code/filestat',7,null,'PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (159,'PJT_CAPA_CODE_JOBLOG',151,'RES_MENU','작업일지','/project/{pjid}/capa/code/joblog',8,null,'PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (160,'PJT_CAPA_CODE_TREND',151,'RES_MENU','활동성향','/project/{pjid}/capa/code/commitTrend/author',9,null,'PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (161,'PJT_CAPA_TASK',150,'RES_MENU','작업생산성','/project/{pjid}/capa/performance',2,'프로젝트 작업생산성','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (162,'PJT_CAPA_COMM',150,'RES_MENU','의사소통성향','/project/{pjid}/capa/talkstendency',3,'프로젝트 의사소통성향','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (163,'PJT_CAPA_AUTHOR',150,'RES_MENU','개발자 기여도','/project/{pjid}/capa/member',4,'프로젝트참여인력','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (164,'PJT_CAPA_REPOSITORY',150,'RES_MENU','SCM 저장소','/project/{pjid}/repository',5,'SCM 저장소','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (458,'PJT_PARTICIPANT_ATTENDANCE',83,'RES_MENU','근태관리','/project/{pjid}/attendance/management',6,'참여인력 근태를 관리합니다.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (459,'PJT_SETTINGS',83,'RES_DYNA_MENU','설정','{1}',11,'','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (461,'PJT_MENU',459,'RES_MENU','메뉴관리','/project/{pjid}/menu',3,'메뉴관리','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (462,'PJT_AUTHORITY',459,'RES_MENU','권한관리','/project/{pjid}/authority',4,'프로젝트 메뉴 권한 조정.','PJ');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (463,'SYS_ATTENDANCE_STANDARD',25,'RES_MENU','근태기준관리','/system/attendanceStandard',4,'근태기준관리','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (464,'SYS_CONFIG_LOGINSCREEN',50,'RES_MENU','로그인화면관리','/system/config/loginScreen',3,'로그인화면관리','NO');
insert into sec_resource(rsc_id, rsc_urn, parent_rsc_id, kind,name,uri,seq,note,mu_type) values (465,'ALL_REPORT',13,'RES_DYNA_MENU','전체보고서','{1}',3,'전체 보고서 메뉴','NO');